//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventlog
    {
        public eventlog()
        {
            this.gwresult = new HashSet<gwresult>();
        }
    
        public int id { get; set; }
        public System.DateTime eventdate { get; set; }
        public int eventplace { get; set; }
        public int responsibleprofessor { get; set; }
        public string eventdescr { get; set; }
    
        public virtual ICollection<gwresult> gwresult { get; set; }
    }
}
