//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class gek
    {
        public gek()
        {
            this.gekmembers = new HashSet<gekmembers>();
            this.gekmembers1 = new HashSet<gekmembers>();
            this.gekmembers2 = new HashSet<gekmembers>();
            this.gekmembers3 = new HashSet<gekmembers>();
            this.gekmembers4 = new HashSet<gekmembers>();
        }
    
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string patronymic { get; set; }
        public string placeofwork { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<gekmembers> gekmembers { get; set; }
        public virtual ICollection<gekmembers> gekmembers1 { get; set; }
        public virtual ICollection<gekmembers> gekmembers2 { get; set; }
        public virtual ICollection<gekmembers> gekmembers3 { get; set; }
        public virtual ICollection<gekmembers> gekmembers4 { get; set; }
    }
}
