//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class geklineup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public geklineup()
        {
            this.gekmembers = new HashSet<gekmembers>();
        }
    
        public int id { get; set; }
        public int groupid { get; set; }
        public int eventid { get; set; }
    
        public virtual eventlog eventlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gekmembers> gekmembers { get; set; }
    }
}
