//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class facultyEntities3 : DbContext
    {
        public facultyEntities3()
            : base("name=facultyEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eventlog> eventlog { get; set; }
        public virtual DbSet<gek> gek { get; set; }
        public virtual DbSet<geklineup> geklineup { get; set; }
        public virtual DbSet<gekmembers> gekmembers { get; set; }
        public virtual DbSet<gwresult> gwresult { get; set; }
        public virtual DbSet<purchaselist> purchaselist { get; set; }
        public virtual DbSet<sciadvisor> sciadvisor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<userrole> userrole { get; set; }
    }
}
