//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaselist
    {
        public int id { get; set; }
        public string purchasename { get; set; }
        public string purchasedescription { get; set; }
        public int sender { get; set; }
        public int quantity { get; set; }
        public int price1pc { get; set; }
        public int overallsum { get; set; }
        public bool ifapproved { get; set; }
    }
}
