//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermProjectFacultyC
{
    using System;
    using System.Collections.Generic;
    
    public partial class sciadvisor
    {
        public sciadvisor()
        {
            this.gekmembers = new HashSet<gekmembers>();
        }
    
        public int id { get; set; }
        public int professor { get; set; }
        public int hoursGW { get; set; }
        public int hoursperGW { get; set; }
        public int takenGWquantity { get; set; }
        public int freeGWquantity { get; set; }
    
        public virtual ICollection<gekmembers> gekmembers { get; set; }
    }
}
